language: java
sudo: false
install: true

addons:
  apt:
    update: true

  sonarcloud:
    organization: "cesardl-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

  sources:
    - mysql-5.7-trusty
  packages:
    - mysql-server
    - mysql-client

jdk:
  - oraclejdk8

git:
  depth: 3

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('rootroot') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - mysql -u root -p rootroot -e "use mysql;source database/ddl_dml.sql;"

script:
  - mvn clean verify
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sonar-scanner; fi

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    - $HOME/.sonarscanner